# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-17 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180816_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.SmallIntegerField(choices=[(1, '周末'), (2, '网络班'), (0, '脱产')], default=0),
        ),
        migrations.AlterField(
            model_name='customerfollowrecord',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '近期无报名计划'), (3, '已报名'), (2, '两周内报名'), (1, '一个月内报名')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='contact_type',
            field=models.SmallIntegerField(choices=[(2, '手机'), (1, '微信'), (0, 'qq')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='source',
            field=models.SmallIntegerField(choices=[(1, '51CTO'), (2, '百度推广'), (4, '转介绍'), (3, '知乎'), (0, 'QQ群'), (5, '其他')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已报名'), (0, '未报名'), (2, '已退学')]),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(0, 'N/A'), (85, 'B+'), (90, 'A'), (-100, 'COPY'), (40, 'C-'), (80, 'B'), (75, 'B-'), (70, 'C+'), (60, 'C'), (-50, 'D'), (100, 'A+')], default=0),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='show_status',
            field=models.SmallIntegerField(choices=[(1, '已到'), (3, '早退'), (0, '缺勤'), (2, '迟到')]),
        ),
    ]
