# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20180820_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfollowrecord',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '两周内报名'), (1, '一个月内报名'), (3, '已报名'), (0, '近期无报名计划')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='contact_type',
            field=models.SmallIntegerField(choices=[(0, 'qq'), (2, '手机'), (1, '微信')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='gender',
            field=models.PositiveIntegerField(blank=True, choices=[(1, ' 女'), (0, '男')], null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='source',
            field=models.SmallIntegerField(choices=[(2, '百度推广'), (3, '知乎'), (5, '其他'), (4, '转介绍'), (1, '51CTO'), (0, 'QQ群')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未报名'), (2, '已退学'), (1, '已报名')]),
        ),
        migrations.AlterField(
            model_name='menus',
            name='url_type',
            field=models.SmallIntegerField(choices=[(0, 'absolute'), (1, 'dynamic')], default=0),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(0, '报名费'), (2, '退费'), (1, '学费')]),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(70, 'C+'), (-100, 'COPY'), (100, 'A+'), (40, 'C-'), (60, 'C'), (75, 'B-'), (80, 'B'), (0, 'N/A'), (85, 'B+'), (-50, 'D'), (90, 'A')], default=0),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='show_status',
            field=models.SmallIntegerField(choices=[(0, '缺勤'), (3, '早退'), (2, '迟到'), (1, '已到')]),
        ),
    ]
