# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20180821_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.CustomerInfo'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.SmallIntegerField(choices=[(1, '周末'), (0, '脱产'), (2, '网络班')], default=0),
        ),
        migrations.AlterField(
            model_name='customerfollowrecord',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '两周内报名'), (0, '近期无报名计划'), (1, '一个月内报名'), (3, '已报名')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='contact_type',
            field=models.SmallIntegerField(choices=[(0, 'qq'), (1, '微信'), (2, '手机')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='gender',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '男'), (1, ' 女')], null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='source',
            field=models.SmallIntegerField(choices=[(3, '知乎'), (5, '其他'), (2, '百度推广'), (1, '51CTO'), (4, '转介绍'), (0, 'QQ群')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已报名'), (2, '已退学'), (0, '未报名')]),
        ),
        migrations.AlterField(
            model_name='menus',
            name='url_type',
            field=models.SmallIntegerField(choices=[(1, 'dynamic'), (0, 'absolute')], default=0),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(2, '退费'), (1, '学费'), (0, '报名费')]),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(40, 'C-'), (100, 'A+'), (90, 'A'), (85, 'B+'), (80, 'B'), (-50, 'D'), (0, 'N/A'), (60, 'C'), (70, 'C+'), (75, 'B-'), (-100, 'COPY')], default=0),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='show_status',
            field=models.SmallIntegerField(choices=[(2, '迟到'), (3, '早退'), (0, '缺勤'), (1, '已到')]),
        ),
    ]
