# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-23 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20180823_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.CustomerInfo'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.SmallIntegerField(choices=[(2, '网络班'), (0, '脱产'), (1, '周末')], default=0),
        ),
        migrations.AlterField(
            model_name='customerfollowrecord',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '近期无报名计划'), (2, '两周内报名'), (3, '已报名'), (1, '一个月内报名')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='source',
            field=models.SmallIntegerField(choices=[(2, '百度推广'), (4, '转介绍'), (1, '51CTO'), (0, 'QQ群'), (3, '知乎'), (5, '其他')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已报名'), (0, '未报名'), (2, '已退学')]),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(-50, 'D'), (0, 'N/A'), (75, 'B-'), (-100, 'COPY'), (60, 'C'), (70, 'C+'), (80, 'B'), (40, 'C-'), (90, 'A'), (85, 'B+'), (100, 'A+')], default=0),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='show_status',
            field=models.SmallIntegerField(choices=[(2, '迟到'), (0, '缺勤'), (1, '已到'), (3, '早退')]),
        ),
    ]
