# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-23 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20180823_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('database_table_list', '可以查看kevinadmin每张表里所有的数据'), ('database_table_list_view', '可以访问kevinadmin表里每条数据的修改页'), ('database_table_list_change', '可以对kevinadmin表里的每条数据进行修改'), ('database_table_obj_add_view', '可以访问kevinadmin每张表的数据增加页'), ('database_table_obj_add', '可以对kevinadmin每张表进行数据添加'), ('database_table_obj_delete', '可以对kevinadmin每张表进行数据删除'), ('database_table_obj_delete_view', '可以对kevinadmin删除时查看所关联的数据'))},
        ),
        migrations.AlterField(
            model_name='classlist',
            name='class_type',
            field=models.SmallIntegerField(choices=[(0, '脱产'), (2, '网络班'), (1, '周末')], default=0),
        ),
        migrations.AlterField(
            model_name='customerfollowrecord',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '近期无报名计划'), (1, '一个月内报名'), (2, '两周内报名'), (3, '已报名')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='contact_type',
            field=models.SmallIntegerField(choices=[(1, '微信'), (0, 'qq'), (2, '手机')]),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='source',
            field=models.SmallIntegerField(choices=[(2, '百度推广'), (4, '转介绍'), (3, '知乎'), (0, 'QQ群'), (5, '其他'), (1, '51CTO')]),
        ),
        migrations.AlterField(
            model_name='menus',
            name='url_type',
            field=models.SmallIntegerField(choices=[(0, 'absolute'), (1, 'dynamic')], default=0),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(2, '退费'), (1, '学费'), (0, '报名费')]),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='score',
            field=models.SmallIntegerField(choices=[(100, 'A+'), (80, 'B'), (70, 'C+'), (40, 'C-'), (90, 'A'), (60, 'C'), (-50, 'D'), (85, 'B+'), (0, 'N/A'), (-100, 'COPY'), (75, 'B-')], default=0),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='show_status',
            field=models.SmallIntegerField(choices=[(0, '缺勤'), (2, '迟到'), (1, '已到'), (3, '早退')]),
        ),
    ]
